### ISSUE TITLE
npm run db migrate results in TypeError: (0 , _rakeDb.change) is not a function

### ISSUE THREAD

**Issue by capaj** [romeerez/orchid-orm-examples#3]
```
in ●  npm run db migrate

> orchid-orm-benchmarks@0.0.0 db
> ts-node src/scripts/db.ts migrate

/home/capaj/oss/orchid-orm-examples/packages/benchmarks/src/migrations/20221117224128_createUser.ts:3
change(async (db) => {
      ^
TypeError: (0 , _rakeDb.change) is not a function
    at Object.<anonymous> (/home/capaj/oss/orchid-orm-examples/packages/benchmarks/src/migrations/20221117224128_createUser.ts:3:7)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module.m._compile (/home/capaj/oss/orchid-orm-examples/packages/benchmarks/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .ts] (/home/capaj/oss/orchid-orm-examples/packages/benchmarks/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /home/capaj/oss/orchid-orm-examples/packages/benchmarks/node_modules/rake-db/src/common.ts:95:9
```

**Comment by capaj** [comment]
it is worth adding that doing npm install as it is in the readme instructions bumps the versions for packages:

![image](https://github.com/romeerez/orchid-orm-examples/assets/1305378/82d3c741-2d7b-493a-8f26-52d0f3bdde47)

I tried using npm ci, but that ends up with 
```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's orchid-orm@1.3.11 does not satisfy orchid-orm@1.9.43
npm ERR! Invalid: lock file's orchid-orm-test-factory@0.1.6 does not satisfy orchid-orm-test-factory@0.2.46
npm ERR! Invalid: lock file's pqb@0.7.8 does not satisfy pqb@0.9.27
npm ERR! Invalid: lock file's rake-db@2.1.11 does not satisfy rake-db@2.8.39
npm ERR! Missing: zapatos@6.1.4 from lock file
npm ERR! Missing: orchid-core@0.4.13 from lock file
npm ERR! Missing: pqb@0.11.35 from lock file
npm ERR! Missing: prompts@2.4.2 from lock file
npm ERR! Invalid: lock file's orchid-orm@1.3.6 does not satisfy orchid-orm@1.5.39
npm ERR! Invalid: lock file's orchid-orm-schema-to-zod@0.1.3 does not satisfy orchid-orm-schema-to-zod@0.2.33
npm ERR! Missing: kleur@3.0.3 from lock file
npm ERR! Missing: sisteransi@1.0.5 from lock file
npm ERR! Missing: pqb@0.11.35 from lock file
npm ERR! 
npm ERR! Clean install a project
```

**Comment by romeerez** [comment]
Oh, interesting, why would it bump the versions.

For now, I'd suggest ignoring the benchmarks, the code is outdated and requires updating.

I was receiving weird results and couldn't understand why is it happening, then I looked through the Drizzle benchmarks and find out that they use a separate Docker instance for each ORM, with a note that Postgres performs some caching-optimizations and to keep it fair needs to run it in separate Docker instances.

So, I'm planning to do the same when I'll have more time. That's why there is [the yellow warning](https://orchid-orm.netlify.app/guide/benchmarks.html) in the benchmarks docs.

But I can assure you that the method of loading relations in Orchid ORM - to do that via `LEFT JOIN LATERAL` - will leave competitors swallowing the dust.

**Comment by capaj** [comment]
good to know.

> to keep it fair needs to run it in separate Docker instances.

you could also just use different DB for each ORM. Docker introduces some skew to the results as running postgres on docker is slower than running on bare metal.

> For now, I'd suggest ignoring the benchmarks, the code is outdated and requires updating.

I was hoping I could run it, add drizzle and open a PR. I really want to see how orchid performs against drizzle.

**Comment by romeerez** [comment]
On simple queries, no wonder Drizzle is faster, because I suppose that Orchid does more stuff under the hood to produce queries. On complex queries, as the [load nested relations](https://orchid-orm.netlify.app/guide/benchmarks.html#load-nested-relation-records), I've seen Drizzle added some support for relations recently but I doubt if it's possible to write this whole query in Drizzle.

It's interesting for me as well, but you see how the folks have begun to open more and more issues in Orchid GitHub, I'm short on time for now.

**Comment by capaj** [comment]
> Drizzle added some support for relations recently but I doubt if it's possible to write this whole query in Drizzle.

I tried it, but it's very limited now. It's not possible with their current API.

>  I'm short on time for now.

too bad orchid does not have a few more maintainers :crying_cat_face:
